version: '3'

services:
    golang:
        container_name: gofiber-projectbase-api-debug      
        env_file: 
            - dev.env  
        build:
            context: .
            dockerfile: Dockerfile.oracle.debug
        ports: 
            - 15300:8080
            - 2345:2345            
        volumes:
            - .:/go/src/github.com/felipeolivers/gofiber-projectbase-api
        networks:
            - gofiber-projectbase-network    

networks:
    gofiber-projectbase-network:
        name: gofiber-projectbase-network
        driver: bridge
        ipam:
            config:
              - subnet: 172.30.2.0/24            